### ISSUE TITLE
F-Droid build crashes when creating a new note

### ISSUE THREAD

**Issue by syphoxy** [OmGodse/Notally#24]
Below is the content of the issue I was initially going to submit but then I decided I'd cut straight to the chase and try the master branch in Android Studio and it appears to work.

I'm not sure if the build in F-Droid needs to be updated or if there's something wrong somewhere else so I'm leaving the remainder of this ticket untouched.

otherwise, app looks great so far. will let you know if there are any issues further issues.

The original issue follows:

---

**App crash when trying to create a new note**

I found this app on F-Droid but when I tried to create a note for the first time, it caused the app to crash and now it crashes every time I try to open the app.

I am using **Android 10** on a Pixel 3 XL and I'm using **Notally v2.6**.

I am able to "reset" by uninstalling the app and installing it again but the crash replicates every time and causes the app to be unopenable.

Replication steps:
1. Open the app
2. Press the plus (+) button
3. Press "Take note"

the app looks good though and I was looking forward to trying it. hopefully this is enough to help you solve the issue. let me know if there's anything I can do to help. I do have some basic experience with Android Studio so if you need me to attach a debugger I could get that done for you.

**Comment by OmGodse** [comment]
So the issue was there when you installed the app from F-Droid but it went away when you built it yourself from the master branch and installed it?

**Comment by syphoxy** [comment]
that is correct.

**Comment by OmGodse** [comment]
Could you try to obtain a stack trace of the crash from the F Droid version and upload it?

**Comment by syphoxy** [comment]
took me a bit to figure out how to do that but here it is. I hope this helps.

```
07-24 01:03:34.734  1350  4289 I ActivityTaskManager: START u0 {cmp=com.omgodse.notally/.activities.TakeNote (has extras)} from uid 10362
07-24 01:03:34.735   895   895 D android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 1
07-24 01:03:34.739  1350  3395 E InputDispatcher: Window handle Window{54d27f4 u0 com.omgodse.notally/com.omgodse.notally.activities.MainActivity} has no registered input channel
07-24 01:03:34.743  3283  3283 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3138 
07-24 01:03:34.743  3283  3283 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1808 
07-24 01:03:34.750  3965  3965 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@9b7d239
07-24 01:03:34.843  3965  3965 D AndroidRuntime: Shutting down VM
07-24 01:03:34.844  3965  3965 E AndroidRuntime: FATAL EXCEPTION: main
07-24 01:03:34.844  3965  3965 E AndroidRuntime: Process: com.omgodse.notally, PID: 3965
07-24 01:03:34.844  3965  3965 E AndroidRuntime: java.util.MissingResourceException: Can't find resource for bundle org.ocpsoft.prettytime.i18n.Resources, key ePattern
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at java.util.ResourceBundle.getObject(ResourceBundle.java:448)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at java.util.ResourceBundle.getObject(ResourceBundle.java:442)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at java.util.ResourceBundle.getString(ResourceBundle.java:405)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at org.ocpsoft.prettytime.i18n.Resources_ja$JaTimeFormat.<init>(Unknown Source:52)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at org.ocpsoft.prettytime.i18n.Resources_ja.a(Unknown Source:12)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at j.a.a.f.b.b(:3)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at j.a.a.b.a(:1)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at j.a.a.b.<init>(:1)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at c.a.a.e.a.d(:11)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at androidx.recyclerview.widget.RecyclerView$v.k(:81)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at androidx.recyclerview.widget.LinearLayoutManager$c.c(:3)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at androidx.recyclerview.widget.LinearLayoutManager.v1(Unknown Source:0)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at androidx.recyclerview.widget.LinearLayoutManager.g1(:2)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at androidx.recyclerview.widget.LinearLayoutManager.u0(:22)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(Unknown Source:38)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at androidx.recyclerview.widget.RecyclerView.dispatchLayout(Unknown Source:37)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(:4)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at androidx.recyclerview.widget.RecyclerView$a.run(Unknown Source:31)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at android.view.Choreographer.doCallbacks(Choreographer.java:791)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at android.view.Choreographer.doFrame(Choreographer.java:722)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at android.os.Handler.handleCallback(Handler.java:883)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:100)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:214)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:7356)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
07-24 01:03:34.844  3965  3965 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
07-24 01:03:34.846  1350  4010 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
07-24 01:03:34.846  1350  3395 W ActivityTaskManager:   Force finishing activity com.omgodse.notally/.activities.TakeNote
07-24 01:03:34.850  1350  3395 W ActivityTaskManager:   Force finishing activity com.omgodse.notally/.activities.MainActivity
```

**Comment by OmGodse** [comment]
Yes, that's very helpful.

After some testing I've found out that the bug is caused by Proguard obfuscating some of PrettyTime's classes for international locales (like JA for Japan).

For the time being, inserting this line in [proguard-rules.pro](https://github.com/OmGodse/Notally/blob/master/app/proguard-rules.pro) fixes the problem.

`-keep class org.ocpsoft.prettytime.** { *; }`

I'll try to optimize it further and will soon release the fixed APK.

**Comment by OmGodse** [comment]
Released the APK with the bug fix. You can either wait for it to roll out on the Play Store or install it from [here](https://github.com/OmGodse/Notally/releases/tag/v2.7)
